import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { inter, fontSans, hanken, playFair } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Habiba Financial Analysis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        fontSans.variable,
        hanken.variable,
        playFair.variable,
        inter.variable,
        "font-inter",
      )}
    >
      <body>{children}</body>
    </html>
  );
}
