import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { inter, fontSans, hanken, playFair } from "@/lib/fonts";

import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: "Habiba Financial Analysis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        fontSans.variable,
        hanken.variable,
        playFair.variable,
        inter.variable,
        "font-inter",
      )}
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
